### ISSUE TITLE
`hydra network provision` new network blocks ICMP requests

### ISSUE THREAD

**Issue by leewardbound** [ShipChain/hydra#15]
I can't figure out why, either, because UFW and IPtables are disabled by default, and only security groups are configured -- they don't allow ICMP either, and they should be modified to do so, but if i go into AWS add the rules by hand, I still can't ping the nodes by public IP.

**Comment by ajhodges** [comment]
@leewardbound did you want me to adjust the sg/ACL to allow ICMP? I made some changes in my branch but haven't done this yet.

**Comment by leewardbound** [comment]
Yes please, not urgent, just nice to have
