### ISSUE TITLE
Segfault after pip install

### ISSUE THREAD

**Issue by leewardbound** [ShipChain/hydra#17]
Not always, but sometimes, when doing *either* `hydra client update` or `pip install git+.../hydra.git`, at the end of the install process on Ubuntu 18.04, there's a segmentation fault.

It seems to be a non-issue, except for the scary warning message, because the package installs correctly and pip has completely cleaned up.

My best guess is that this is problem upstream in maybe the Cement library, because our pip install process is fairly vanilla from their template, but I can't find any other references to the issue on their bug tracker.

**Comment by ajhodges** [comment]
I wanna say we decided this happens when you try to update when you're already up to date? Something weird like that.

**Comment by leewardbound** [comment]
I expect it has a 50-50 chance to disappear when we switch to pypi for distribution anyhow, I'm quite unconcerned with it, just wanted some documentation of it here

**Comment by ajhodges** [comment]
I believe this is related to this issue: https://github.com/pypa/pip/issues/5366

Updating pip fixes this - but I'm not finding a 'good' way to upgrade ubuntu's system 'pip3', that we've been recommending people to use. Looks like it's stuck at pip==9.0.1. If we try to upgrade the debian pip, the [pip3 command breaks](https://github.com/pypa/pip/issues/5221).

Potential solutions:
- Add a line to `sudo pip3 install --upgrade pip` to the install guide. This 'works', it installs pip3 at /usr/local/bin/pip3, but there still exists a broken system pip3 at /usr/bin/pip3. However, (at least on my system) it looks like /usr/local/bin is evaluated in my path before /usr/bin so my `pip3` is the updated one.
- Tell people to `pip3 install --upgrade pip` - this will break `pip3`, but `pip` will now point to the latest (python3) pip. There could be conflicts with this if the user also has python2 pip installed. If there are conflicts with a python2 `pip`, pip3 can always be accessed via `python3 -m pip {command}`.
- Change our ubuntu install instructions from recommending the installation of `python3-pip` to using the `get-pip` script here: https://pip.pypa.io/en/stable/installing/ which will avoid these issues altogether
- Change our install instructions to use a virtualenv, or installing pip/python packages as `--user`, and then using `get-pip` ^

**Comment by leewardbound** [comment]
Honestly I'm tempted to choose #5, not our bug not our problem, but do feel free to add whatever makes you happy to the validator install guide

**Comment by ajhodges** [comment]
I think we're going to say that anyone encountering this issue should use `sudo pip3 install --upgrade pip` to resolve it. But if you are using python for other things on your server, please be aware of the implications - you'll be effectively breaking the debian `python3-pip` package.

**Comment by ajhodges** [comment]
New recommendation:
`sudo apt remove python3-pip`
`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
`python3 get-pip.py --user`

This avoids any permission issues when installing hydra.
